### ISSUE TITLE
kmean error

### ISSUE THREAD

**Issue by mupsje** [hancock-da/crypto-scanners#1]
getting a error when run

kmeans_resistance_scanner.py", line 75, in <module>
    if result:
NameError: name 'result' is not defined

Needed also to remove the backtesting
from line 44 and 47 now its just "/datasets/1d_datasets"

please advice
greets Remco

**Comment by hancock-da** [comment]
Thanks for pointing it out - I have fixed the 'result' error and altered the code a bit so that you can easily set the dataset path at the top to either 1D / 4H or data in any other timeframe downloaded by the scanner.
